name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # Ganti dengan versi PHP yang sesuai

      - name: Copy .env.example to .env
        run: cp ./INKOSTEL/.env ./INKOSTEL/.env.backup

      - name: Run Composer
        run: composer install --no-interaction
        working-directory: ./INKOSTEL

      - name: Run tests
        run: php artisan test
        working-directory: ./INKOSTEL


